/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbankapplication;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Madiha
 */
public class BloodBagManagementForm extends javax.swing.JFrame {
      
    public BloodBagManagementForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aApositive = new javax.swing.JButton();
        rApositve = new javax.swing.JButton();
        aAnegative = new javax.swing.JButton();
        aABpositive = new javax.swing.JButton();
        aABnegative = new javax.swing.JButton();
        aBpositive = new javax.swing.JButton();
        aBnegative = new javax.swing.JButton();
        aOpositive = new javax.swing.JButton();
        aOnegative = new javax.swing.JButton();
        rAnegative = new javax.swing.JButton();
        rABpositve = new javax.swing.JButton();
        rABnegative = new javax.swing.JButton();
        rBpositve = new javax.swing.JButton();
        rBnegative = new javax.swing.JButton();
        rOpositve = new javax.swing.JButton();
        rOnegative = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    A+");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    A-");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   AB+");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   AB-");

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    B+");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("    B-");

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("    O+");

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("    O-");

        aApositive.setBackground(new java.awt.Color(255, 0, 0));
        aApositive.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aApositive.setForeground(new java.awt.Color(255, 255, 255));
        aApositive.setText("ADD");
        aApositive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aApositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aApositiveActionPerformed(evt);
            }
        });

        rApositve.setBackground(new java.awt.Color(255, 0, 0));
        rApositve.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rApositve.setForeground(new java.awt.Color(255, 255, 255));
        rApositve.setText("REMOVE");
        rApositve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rApositve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rApositveActionPerformed(evt);
            }
        });

        aAnegative.setBackground(new java.awt.Color(255, 0, 0));
        aAnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aAnegative.setForeground(new java.awt.Color(255, 255, 255));
        aAnegative.setText("ADD");
        aAnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aAnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAnegativeActionPerformed(evt);
            }
        });

        aABpositive.setBackground(new java.awt.Color(255, 0, 0));
        aABpositive.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aABpositive.setForeground(new java.awt.Color(255, 255, 255));
        aABpositive.setText("ADD");
        aABpositive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aABpositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aABpositiveActionPerformed(evt);
            }
        });

        aABnegative.setBackground(new java.awt.Color(255, 0, 0));
        aABnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aABnegative.setForeground(new java.awt.Color(255, 255, 255));
        aABnegative.setText("ADD");
        aABnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aABnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aABnegativeActionPerformed(evt);
            }
        });

        aBpositive.setBackground(new java.awt.Color(255, 0, 0));
        aBpositive.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aBpositive.setForeground(new java.awt.Color(255, 255, 255));
        aBpositive.setText("ADD");
        aBpositive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aBpositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBpositiveActionPerformed(evt);
            }
        });

        aBnegative.setBackground(new java.awt.Color(255, 0, 0));
        aBnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aBnegative.setForeground(new java.awt.Color(255, 255, 255));
        aBnegative.setText("ADD");
        aBnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aBnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBnegativeActionPerformed(evt);
            }
        });

        aOpositive.setBackground(new java.awt.Color(255, 0, 0));
        aOpositive.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aOpositive.setForeground(new java.awt.Color(255, 255, 255));
        aOpositive.setText("ADD");
        aOpositive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aOpositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aOpositiveActionPerformed(evt);
            }
        });

        aOnegative.setBackground(new java.awt.Color(255, 0, 0));
        aOnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        aOnegative.setForeground(new java.awt.Color(255, 255, 255));
        aOnegative.setText("ADD");
        aOnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aOnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aOnegativeActionPerformed(evt);
            }
        });

        rAnegative.setBackground(new java.awt.Color(255, 0, 0));
        rAnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rAnegative.setForeground(new java.awt.Color(255, 255, 255));
        rAnegative.setText("REMOVE");
        rAnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rAnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAnegativeActionPerformed(evt);
            }
        });

        rABpositve.setBackground(new java.awt.Color(255, 0, 0));
        rABpositve.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rABpositve.setForeground(new java.awt.Color(255, 255, 255));
        rABpositve.setText("REMOVE");
        rABpositve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rABpositve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rABpositveActionPerformed(evt);
            }
        });

        rABnegative.setBackground(new java.awt.Color(255, 0, 0));
        rABnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rABnegative.setForeground(new java.awt.Color(255, 255, 255));
        rABnegative.setText("REMOVE");
        rABnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rABnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rABnegativeActionPerformed(evt);
            }
        });

        rBpositve.setBackground(new java.awt.Color(255, 0, 0));
        rBpositve.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rBpositve.setForeground(new java.awt.Color(255, 255, 255));
        rBpositve.setText("REMOVE");
        rBpositve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rBpositve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBpositveActionPerformed(evt);
            }
        });

        rBnegative.setBackground(new java.awt.Color(255, 0, 0));
        rBnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rBnegative.setForeground(new java.awt.Color(255, 255, 255));
        rBnegative.setText("REMOVE");
        rBnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rBnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBnegativeActionPerformed(evt);
            }
        });

        rOpositve.setBackground(new java.awt.Color(255, 0, 0));
        rOpositve.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rOpositve.setForeground(new java.awt.Color(255, 255, 255));
        rOpositve.setText("REMOVE");
        rOpositve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rOpositve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOpositveActionPerformed(evt);
            }
        });

        rOnegative.setBackground(new java.awt.Color(255, 0, 0));
        rOnegative.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        rOnegative.setForeground(new java.awt.Color(255, 255, 255));
        rOnegative.setText("REMOVE");
        rOnegative.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rOnegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOnegativeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BLOOD BAG MANAGEMENT");

        back.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 79, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aApositive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aAnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aABpositive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aABnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aBpositive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aBnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aOpositive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aOnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rOnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rOpositve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBpositve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rABnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rABpositve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rAnegative, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rApositve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(aApositive)
                            .addComponent(rApositve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(aAnegative)
                            .addComponent(rAnegative))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(aABpositive)
                            .addComponent(rABpositve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(aABnegative)
                            .addComponent(rABnegative))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(aBpositive)
                                .addComponent(rBpositve)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(rBnegative)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(aBnegative)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aOpositive)
                    .addComponent(rOpositve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(aOnegative)
                    .addComponent(rOnegative))
                .addGap(18, 18, 18)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void rApositveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rApositveActionPerformed
       removeBlood("A+");
       JOptionPane.showMessageDialog(this, "A+ bag removed.");
        // TODO add your handling code here:
    }//GEN-LAST:event_rApositveActionPerformed
    private void rAnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAnegativeActionPerformed
       removeBlood("A-");
       JOptionPane.showMessageDialog(this, "A- bag removed.");// TODO add your handling code here:
    }//GEN-LAST:event_rAnegativeActionPerformed
    private void rABpositveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rABpositveActionPerformed
       removeBlood("AB+");
       JOptionPane.showMessageDialog(this, "AB+ bag removed.");// TODO add your handling code here:
    }//GEN-LAST:event_rABpositveActionPerformed

    private void rABnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rABnegativeActionPerformed
       removeBlood("AB-");
       JOptionPane.showMessageDialog(this, "AB- bag removed.");// TODO add your handling code here:
    }//GEN-LAST:event_rABnegativeActionPerformed
    private void rBpositveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBpositveActionPerformed
       removeBlood("B+");
       JOptionPane.showMessageDialog(this, "B+ bag removed.");  // TODO add your handling code here:
    }//GEN-LAST:event_rBpositveActionPerformed

    private void rBnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBnegativeActionPerformed
       removeBlood("B-");
       JOptionPane.showMessageDialog(this, "B- bag removed."); // TODO add your handling code here:
    }//GEN-LAST:event_rBnegativeActionPerformed

    private void rOpositveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOpositveActionPerformed
       removeBlood("O+");
       JOptionPane.showMessageDialog(this, "O+ bag removed."); 
    }//GEN-LAST:event_rOpositveActionPerformed

    private void rOnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOnegativeActionPerformed
       removeBlood("O-");
       JOptionPane.showMessageDialog(this, "O- bag removed.");   // TODO add your handling code here:
    }//GEN-LAST:event_rOnegativeActionPerformed

    private void aApositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aApositiveActionPerformed
             addBlood("A+");
             JOptionPane.showMessageDialog(this, "A+ bag added."); // TODO add your handling code here:
    }//GEN-LAST:event_aApositiveActionPerformed

    private void aAnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAnegativeActionPerformed
             addBlood("A-");
             JOptionPane.showMessageDialog(this, "A- bag added."); // TODO add your handling code here:
    }//GEN-LAST:event_aAnegativeActionPerformed

    private void aABpositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aABpositiveActionPerformed
             addBlood("AB+");
             JOptionPane.showMessageDialog(this, "AB+ bag added.");// TODO add your handling code here:
    }//GEN-LAST:event_aABpositiveActionPerformed

    private void aABnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aABnegativeActionPerformed
             addBlood("AB-");
             JOptionPane.showMessageDialog(this, "AB- bag added.");
    }//GEN-LAST:event_aABnegativeActionPerformed

    private void aBpositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBpositiveActionPerformed
             addBlood("B+");
             JOptionPane.showMessageDialog(this, "B+ bag added.");// TODO add your handling code here:
    }//GEN-LAST:event_aBpositiveActionPerformed

    private void aBnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBnegativeActionPerformed
             addBlood("B-");
             JOptionPane.showMessageDialog(this, "B- bag added.");
// TODO add your handling code here:
    }//GEN-LAST:event_aBnegativeActionPerformed

    private void aOpositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aOpositiveActionPerformed
             addBlood("O+");
             JOptionPane.showMessageDialog(this, "O+ bag added."); // TODO add your handling code here:
    }//GEN-LAST:event_aOpositiveActionPerformed

    private void aOnegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aOnegativeActionPerformed
             addBlood("O-");
             JOptionPane.showMessageDialog(this, "O- bag added.");   // TODO add your handling code here:
    }//GEN-LAST:event_aOnegativeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MainDashboard().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed
private void addBlood(String bloodGroup) {
         String dbURL = "jdbc:ucanaccess://C:/Users/USER/Documents/bloodbank.accdb";
    try (Connection con = DriverManager.getConnection(dbURL);
) {
        PreparedStatement psSelect = con.prepareStatement(
            "SELECT Received, Donated FROM bloodbaginfo WHERE [Blood Group]=?"
        );
        psSelect.setString(1, bloodGroup);
        ResultSet rs = psSelect.executeQuery();

        if (rs.next()) {
            int received = rs.getInt("Received") + 1;
            int donated  = rs.getInt("Donated");
            int available = received - donated;

            PreparedStatement psUpdate = con.prepareStatement(
                "UPDATE bloodbaginfo SET [Received]=?, [Available]=? WHERE [Blood Group]=?"
            );
            psUpdate.setInt(1, received);
            psUpdate.setInt(2, available);
            psUpdate.setString(3, bloodGroup);
            psUpdate.executeUpdate();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
private void removeBlood(String bloodGroup) {
    String dbURL = "jdbc:ucanaccess://C:/Users/USER/Documents/bloodbank.accdb";
    try(Connection con = DriverManager.getConnection(dbURL)){

        PreparedStatement psSelect = con.prepareStatement(
            "SELECT Received, Donated FROM bloodbaginfo WHERE [Blood Group]=?"
        );
        psSelect.setString(1, bloodGroup);
        ResultSet rs = psSelect.executeQuery();

        if (rs.next()) {
            int received = rs.getInt("Received");
            int donated  = rs.getInt("Donated");

            if (received - donated <= 0) {
                JOptionPane.showMessageDialog(this, "No blood available!");
                return;
            }

            donated++;
            int available = received - donated;

            PreparedStatement psUpdate = con.prepareStatement(
                "UPDATE bloodbaginfo SET [Donated]=?, [Available]=? WHERE [Blood Group]=?"
            );
            psUpdate.setInt(1, donated);
            psUpdate.setInt(2, available);
            psUpdate.setString(3, bloodGroup);
            psUpdate.executeUpdate();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodBagManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodBagManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodBagManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodBagManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new BloodBagManagementForm().setVisible(true);
}

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aABnegative;
    private javax.swing.JButton aABpositive;
    private javax.swing.JButton aAnegative;
    private javax.swing.JButton aApositive;
    private javax.swing.JButton aBnegative;
    private javax.swing.JButton aBpositive;
    private javax.swing.JButton aOnegative;
    private javax.swing.JButton aOpositive;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rABnegative;
    private javax.swing.JButton rABpositve;
    private javax.swing.JButton rAnegative;
    private javax.swing.JButton rApositve;
    private javax.swing.JButton rBnegative;
    private javax.swing.JButton rBpositve;
    private javax.swing.JButton rOnegative;
    private javax.swing.JButton rOpositve;
    // End of variables declaration//GEN-END:variables
}
